#服务端口
server:
  port: 10086
#eureka服务名
spring:
  application:
    name: eurekaserver
#eureka地址信息
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

#ribbon:
#  eager-load:
#    enabled: true
#    clients:
#      - userservice
